ports:
- port: 3000
  onOpen: ignore

tasks:
- openIn: right
  name: Test Suite Server
  command: python -m SimpleHTTPServer 3000
- openIn: bottom
  name: Shell 1
- openIn: bottom
  name: Shell 2
- openIn: bottom
  name: Python
  command: python3
